#!/bin/bash

# Usage
# -----
# cvim branding/templates/login.tmpl:29
#
# This will take you directly to line number 29

file=`echo $1|cut -d: -f1`
pointer=`echo $1|cut -d: -f2`
line="+$pointer"
if [[ $1 != *:* ]] || [[ $pointer -le 0 ]]
  then
    #pointer=1
    line=''
fi

vim $file $line
